"""Write one MIC config per pair and seed into mic/configs/rose/.

Each file inherits mic_daformer_rose_512x512.py and sets the source/target data
roots (inside MIC: data/rose/{domain}/), the target split for that seed, and the seed.
With --smoke, also writes {pair}_s{first seed}_smoke.py: 50 iterations, eval at the end.
"""
import argparse
from pathlib import Path

from weedrefine.data.splits import domain_name
from weedrefine.utils.io import load_yaml

TEMPLATE = """# Generated by scripts/make_mic_configs.py from {pair_cfg}. Do not edit by hand.
_base_ = ['mic_daformer_rose_512x512.py']
seed = {seed}
name = '{name}'
src_root = 'data/rose/{src}/'
tgt_root = 'data/rose/{tgt}/'
data = dict(
    train=dict(
        source=dict(data_root=src_root, img_suffix='{src_suffix}', split='splits/all.txt'),
        target=dict(data_root=tgt_root, img_suffix='{tgt_suffix}',
                    split='splits/seed{seed}_train.txt')),
    val=dict(data_root=tgt_root, img_suffix='{tgt_suffix}', split='splits/seed{seed}_val.txt'),
    test=dict(data_root=tgt_root, img_suffix='{tgt_suffix}', split='splits/seed{seed}_val.txt'))
"""

SMOKE = """
# Smoke test: a few iterations to check the setup runs end to end.
runner = dict(type='IterBasedRunner', max_iters=50)
checkpoint_config = dict(by_epoch=False, interval=50, max_keep_ckpts=1)
evaluation = dict(interval=50, metric='mIoU')
log_config = dict(interval=10, img_interval=50)
"""


def image_suffix(data_dir, domain):
    imgs = sorted((Path(data_dir) / domain / "img").glob("*"))
    return imgs[0].suffix if imgs else ".jpg"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", nargs="+", required=True)
    ap.add_argument("--data", default="data/mic", help="output of prepare_mic_data.py")
    ap.add_argument("--out", default="mic/configs/rose")
    ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    for p in args.pairs:
        cfg = load_yaml(p)
        src = domain_name(*(cfg["source"][k] for k in ("team", "crop", "year")))
        tgt = domain_name(*(cfg["target"][k] for k in ("team", "crop", "year")))
        fields = dict(pair_cfg=p, src=src, tgt=tgt,
                      src_suffix=image_suffix(args.data, src),
                      tgt_suffix=image_suffix(args.data, tgt))
        for seed in cfg["seeds"]:
            name = f"{cfg['name']}_s{seed}"
            (out / f"{name}.py").write_text(TEMPLATE.format(seed=seed, name=name, **fields))
            print("wrote", out / f"{name}.py")
        if args.smoke:
            seed = cfg["seeds"][0]
            name = f"{cfg['name']}_s{seed}_smoke"
            (out / f"{name}.py").write_text(
                TEMPLATE.format(seed=seed, name=name, **fields) + SMOKE)
            print("wrote", out / f"{name}.py")


if __name__ == "__main__":
    main()
