# Generated by scripts/make_mic_configs.py from configs/pairs/bean_2019_to_2021.yaml. Do not edit by hand.
_base_ = ['mic_daformer_rose_512x512.py']
seed = 0
name = 'bean_2019_to_2021_s0_smoke'
src_root = 'data/rose/bipbip_haricot_2019/'
tgt_root = 'data/rose/bipbip_haricot_2021/'
data = dict(
    train=dict(
        source=dict(data_root=src_root, img_suffix='.jpg', split='splits/all.txt'),
        target=dict(data_root=tgt_root, img_suffix='.jpg',
                    split='splits/seed0_train.txt')),
    val=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'),
    test=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'))

# Smoke test: a few iterations to check the setup runs end to end.
runner = dict(type='IterBasedRunner', max_iters=50)
checkpoint_config = dict(by_epoch=False, interval=50, max_keep_ckpts=1)
evaluation = dict(interval=50, metric='mIoU')
log_config = dict(interval=10, img_interval=50)
