# Generated by scripts/make_mic_configs.py from configs/pairs/maize_2019_to_2021.yaml. Do not edit by hand.
_base_ = ['mic_daformer_rose_512x512.py']
seed = 0
name = 'maize_2019_to_2021_s0'
src_root = 'data/rose/bipbip_mais_2019/'
tgt_root = 'data/rose/bipbip_mais_2021/'
data = dict(
    train=dict(
        source=dict(data_root=src_root, img_suffix='.jpg', split='splits/all.txt'),
        target=dict(data_root=tgt_root, img_suffix='.jpg',
                    split='splits/seed0_train.txt')),
    val=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'),
    test=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'))
