# Generated by scripts/make_mic_configs.py from configs/pairs/maize_2019_to_2021.yaml. Do not edit by hand.
_base_ = ['mic_daformer_rose_512x512.py']
seed = 0
name = 'maize_2019_to_2021_s0_10k'
src_root = 'data/rose/bipbip_mais_2019/'
tgt_root = 'data/rose/bipbip_mais_2021/'
data = dict(
    train=dict(
        source=dict(data_root=src_root, img_suffix='.jpg', split='splits/all.txt'),
        target=dict(data_root=tgt_root, img_suffix='.jpg',
                    split='splits/seed0_train.txt')),
    val=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'),
    test=dict(data_root=tgt_root, img_suffix='.jpg', split='splits/seed0_val.txt'))

# Shorter schedule than the base 40k. Poly LR decay follows max_iters; warmup stays 1500.
runner = dict(type='IterBasedRunner', max_iters=10000)
checkpoint_config = dict(by_epoch=False, interval=2000, max_keep_ckpts=1)
evaluation = dict(interval=1000, metric='mIoU')
