# MIC (DAFormer, MiT-B5, sep. ASPP decoder) on ROSE crop/weed, 512x512 crops.
# Copied into third_party/MIC/seg/configs/rose/ by scripts/install_mic_rose.sh.
# Per pair/seed configs (generated by scripts/make_mic_configs.py) set data paths,
# split files and seed on top of this file.
#
# Follows MIC's DAFormer variant in experiments.py (exp 81, 'daformer_sepaspp',
# 'dacs_a999_fdthings', rcs 0.01, mask 32 / 0.7, AdamW 6e-5, poly10warm, 40k).
# MaskAdapt: "MIC is the base architecture with MiT-B5 ... and ASPP decode head as
# context-aware feature fusion decoder" (no HRDA mentioned), so no HRDA here.
# Lines marked CHOICE are ours; MaskAdapt does not state them.

_base_ = [
    '../_base_/default_runtime.py',
    '../_base_/models/daformer_sepaspp_mitb5.py',
    '../_base_/uda/dacs_a999_fdthings.py',
    '../_base_/schedules/adamw.py',
    '../_base_/schedules/poly10warm.py',
]

model = dict(decode_head=dict(num_classes=3))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
# CHOICE: resize every image to fit 1024x768 (keep ratio). Bipbip 2019 is 2048x1536,
# 2021 is 1024x768, so both end up 1024x768.
img_scale = (1024, 768)
source_train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    # PhotoMetricDistortion is applied later in dacs.py
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
target_train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=img_scale),
    dict(type='RandomCrop', crop_size=crop_size),
    dict(type='RandomFlip', prob=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

# Paths are filled in by the generated per pair/seed configs.
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='UDADataset',
        source=dict(type='ROSEDataset', img_dir='img', ann_dir='ann',
                    pipeline=source_train_pipeline),
        target=dict(type='ROSEDataset', img_dir='img', ann_dir='ann',
                    pipeline=target_train_pipeline),
        # Rare class sampling as in MIC/DAFormer 512 crops.
        rare_class_sampling=dict(min_pixels=3000, class_temp=0.01, min_crop_ratio=0.5)),
    val=dict(type='ROSEDataset', img_dir='img', ann_dir='ann', pipeline=test_pipeline),
    test=dict(type='ROSEDataset', img_dir='img', ann_dir='ann', pipeline=test_pipeline))

uda = dict(
    # CHOICE: ImageNet feature distance on the plant classes (crop, weed) instead of
    # the Cityscapes "thing" classes [6, 7, 11, ...] in dacs_a999_fdthings.py.
    imnet_feature_dist_classes=[1, 2],
    # CHOICE: no pseudo-label top/bottom cropping (MIC uses 15/120 px to hide the
    # Cityscapes ego car; ROSE has no such border).
    pseudo_weight_ignore_top=0,
    pseudo_weight_ignore_bottom=0,
    # MIC masking, DAFormer resolution settings from MIC experiments.py.
    mask_mode='separatetrgaug',
    mask_alpha='same',
    mask_pseudo_threshold='same',
    mask_lambda=1,
    mask_generator=dict(type='block', mask_ratio=0.7, mask_block_size=32, _delete_=True))

optimizer_config = None
optimizer = dict(
    lr=6e-05,
    paramwise_cfg=dict(
        custom_keys=dict(
            head=dict(lr_mult=10.0),
            pos_block=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0))))
n_gpus = 1
iters = 40000
runner = dict(type='IterBasedRunner', max_iters=iters)
checkpoint_config = dict(by_epoch=False, interval=iters, max_keep_ckpts=1)
evaluation = dict(interval=iters // 10, metric='mIoU')
exp = 'rose'
